# Bounding box
x_min: -25
x_max: 7
y_min: -28
y_max: 60
z_min: -1.1
z_max: 5

base_height: 1.5
base_radius: 0.2
connection_radius: 4.0
too_close_threshold: 1.0 # 1.0
robot_type: 0
raywalking_max_height_diff: 0.2
exploration_mode: true
min_hit_ratio: 0.5

# Start positions
start:
  x: 1.0
  y: 0.0
  z: 1.0 # robot 

# Thresholds
frontier_creation_threshold: 0.3
frontier_jump_threshold: 1.5
frontier_split_threshold: 2.0
min_flowback_creation_threshold: 1
min_flowback_creation_radius_threshold: 0.25
bad_loop: true

# Ray and node settings
min_node_radius: 0.8
search_margin: 0.1
max_ray_length: 2.5
max_expansion_ray_length: 2.5
max_height_diff: 1.5
sampling_density: 100
max_facets_grouped: 10
resolution: 0.1
