# Bounding box
x_min: -15
x_max: 6
y_min: -12.5
y_max: 12.5
z_min: -1
z_max: 4

# Start positions
start:
  x: 0.0
  y: 0.0
  z: 0.5

#1.83343 2.9898 -0.0913357
#3.41294 2.82653 0.32438
path_start:
  x: 1.83343
  y: 1.9898
  z: 1

path_target:
  x: 1.8
  y: 2.4
  z: 1

# General settings
is_simulation: false

# Thresholds
frontier_creation_threshold: 0.3
frontier_jump_threshold: 3.0
frontier_split_threshold: 2.0
min_flowback_creation_threshold: 1
min_flowback_creation_radius_threshold: 0.1

# Ray and node settings
min_node_radius: 2.0
search_margin: 0.4
max_ray_length: 3.0
max_expansion_ray_length: 3.0
max_height_diff: 0.5
sampling_density: 50
max_facets_grouped: 10
resolution: 0.1

truncated_z_high: 4
truncated_z_low: -2

# Debug and visualization
debug_mode: false
bad_loop: true
visualize_final_result_only: true
visualize_all: false
visualize_outwards_normal: false
visualize_nbhd_frontiers: false
visualize_black_polygon: false

# Removed unused parameters
map_representation: 0
visualize_nbhd_facets: false